version: "3.7"

services:
  database_tcc:
    image: postgres
    container_name: database_tcc
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=tcc
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

volumes:
  pgdata:
    driver: local
